### PR TITLE
fix: local entity index query failed when index was missing from local data

### PR DESCRIPTION
**Pull request by thantos**
If the .eventual/local folder was missing an index (new/deleted), `index.query` would fail on query. change the logic to create requested indices on demand if they were not originally loaded.

TODO: Compute missing local indices on load for existing data https://github.com/functionless/eventual/issues/464

### CODE REVIEW

**Comment by sam-goodwin** [comment]
Should local compute the indexes instead of persisting

**Comment by thantos** [comment]
Yeah, I added a TODO to do that, just wanted to fix the breaking issue in this change. Added a TODO and issue https://github.com/functionless/eventual/issues/464.

**Comment by sam-goodwin** [comment]
What's left to do here? Fix tests?

**Review by sam-goodwin — APPROVED** [review]

**Comment by thantos** [comment]
Uhh, yeah, the tests randomly fail, don't think it is the fault of this change. Will keep an eye on it today.

**Pull request merged**
